config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  namespace :api do
  	namespace :v1, defaults: {format: :json} do
  		resources :articles, only: [:index]

  	end
  end
  
  resources :articles
  root 'articles#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	validates :title, uniqueness: true
	validates :validated, acceptance: { message: 'must be accepted' }
end

app/controllers/api/v1/articles_controller.rb
class Api::V1::ArticlesController < ApplicationController
	def index
    @articles = Article.all
    
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

	def new
		@article = Article.new
	end

    def create
    	@article = Article.new(params.require(:article).permit(:title,:author,:text,:validated))
    	#binding.pry
    	if @article.save
    		redirect_to @article
  		else
  			@article.save!
  			render :action => 'new'
  		end
    end

    def show
    	@article = Article.find(params[:id])
    end

    def index
    	@article = Article.all.order(title: :asc)
    end

    def edit
    	@article = Article.find(params[:id])
    end

    def update
    	@article = Article.find(params[:id])

    	if @article.update_attributes(params.require(:article).permit(:title,:text))
    		@article.save
    		redirect_to :action => 'show' , :id => @article
    	else
    		render :action => 'edit'
    	end
    end

    def destroy
    	@article = Article.find(params[:id])
    	@article.destroy
    	redirect_to articles_path
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/destroy.html.erb
<%= link_to 'destroy', article_path(article), method: :delete, data: { confirm: 'Are you sure?'}%>

app/views/articles/edit.html.erb
<h1> New Article </h1>

<%=form_for @article, url: article_path do |f| %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :text %><br>
		<%= f.text_area :text %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1> List of articles </h1>

<table>
	<tr>
		<th>Title</th>
		<th>Author</th>
		<th>Text</th>
		<th>Is Checked </th>t
		<th>Time-created</th>
	</tr>

	<% @article.each do |article| %>
	<tr>
		<td><%= article.title %></td>
		<td><%= article.author %></td>
		<td><%= article.text %></td>
		<td><%= article.validated %></td>
		<td><%= article.created_at %></td>
		<td><%= link_to 'show', article_path(article) %></td>
		<td><%= link_to 'edit', edit_article_path(article) %></td>
		<td> <%= link_to 'destroy', article_path(article), method: :delete, data: { confirm: 'Are you sure?'}%>
	</tr>
	<% end %>
</table>

app/views/articles/new.html.erb
<h1> New Article </h1>

<%=form_for :article, url: articles_path do |f| %>
	<p>
		<%= f.label :title %><br>
		<%= f.text_field :title %><br>
	</p>

	<p>
		<%= f.label :author %><br>
		<%= f.text_field :author %><br>
	</p>

	<p>
		<%= f.label :text %><br>
		<%= f.text_area :text %>
	</p>

	<p>

		<%= f.check_box :validated %> accept
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>

app/views/articles/show.html.erb
<h1> Show Page </h1>

<p>
	<strong>Title:</strong>
	<%= @article.title %>
</p>

<p>
	<strong>Author:</strong>
	<%= @article.author %>
</p>

<p>
	<strong>Text:</strong>
	<%= @article.text %>
</p>

<p>
	<strong>is checked?</strong>
	<%= @article.validated %>
</p>
<p>
	<strong>Time:</strong>
	<%= @article.created_at %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FirstApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <body bgcolor="#E6E6FA">
    <%= yield %>
  </body>
</html>